apiVersion: v1
kind: Service
metadata:
  name: liberu-automation
  namespace: liberu-automation
  labels:
    app: liberu-automation
spec:
  selector:
    app: liberu-automation
    component: application
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
