name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: sqlite3, pdo_sqlite

    - name: Copy environment file
      run: cp .env.testing .env
      
    - name: Install dependencies
      run: composer install
      
    - name: Generate application key
      run: php artisan key:generate
      
    - name: Run tests
      run: vendor/bin/phpunit --no-coverage
    
